server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: citizenModule
          uri: http://localhost:8082/
          predicates:
            - Path=/api/person/**
        - id: passportModule
          uri: http://localhost:8084/
          predicates:
            - Path=/api/passport/**
        - id: carModule
            uri: http://localhost:8081/
            predicates:
              - Path=/api/car**
        - id: houseModule
            uri: http://localhost:8083/
            predicates:
              - Path=/api/house/**