spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://127.0.0.1:9000
#          jwk-set-uri: http://127.0.0.1:9000/oauth2/jwks
  application:
    name: citizen-micro
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring-city-citizens
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
server:
  port: 8082
#websocket: ws://localhost:8090/websocket-server
#  value: ws://localhost:8090/websocket-server

