spring:
#  kafka:
#    producer:
#      bootstrap-servers: localhost:29092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.trusted.packages: "*"
##        spring.json.type.mapping: com.nikitalipatov.citizens.kafka.DeletePersonDto
##        spring.json.add.type.headers: false
#    consumer:
#      group-id: test-gi
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
##        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
#        spring.json.trusted.packages: "*"
##        spring.json.type.mapping: com.nikitalipatov.citizens.kafka.DeletePersonDto
#    bootstrap-servers: localhost:29092
#    properties:
#      spring.json.trusted.packages: "*"
##      spring.json.add.type.headers: false


  application:
    name: citizen-micro
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring-city-citizens
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
server:
  port: 8082

